# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: devrpc/dev.proto

require 'google/protobuf'

require 'lightning_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("devrpc/dev.proto", :syntax => :proto3) do
    add_message "devrpc.ImportGraphResponse" do
    end
  end
end

module Devrpc
  ImportGraphResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("devrpc.ImportGraphResponse").msgclass
end
