# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: devrpc/dev.proto for package 'devrpc'

require 'grpc'
require 'devrpc/dev_pb'

module Devrpc
  module Dev
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'devrpc.Dev'

      #
      # ImportGraph imports a ChannelGraph into the graph database. Should only be
      # used for development.
      rpc :ImportGraph, ::Lnrpc::ChannelGraph, ::Devrpc::ImportGraphResponse
    end

    Stub = Service.rpc_stub_class
  end
end
