# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: invoicesrpc/invoices.proto

require 'google/protobuf'

require 'rpc_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("invoicesrpc/invoices.proto", :syntax => :proto3) do
    add_message "invoicesrpc.CancelInvoiceMsg" do
      optional :payment_hash, :bytes, 1
    end
    add_message "invoicesrpc.CancelInvoiceResp" do
    end
    add_message "invoicesrpc.AddHoldInvoiceRequest" do
      optional :memo, :string, 1
      optional :hash, :bytes, 2
      optional :value, :int64, 3
      optional :value_msat, :int64, 10
      optional :description_hash, :bytes, 4
      optional :expiry, :int64, 5
      optional :fallback_addr, :string, 6
      optional :cltv_expiry, :uint64, 7
      repeated :route_hints, :message, 8, "lnrpc.RouteHint"
      optional :private, :bool, 9
    end
    add_message "invoicesrpc.AddHoldInvoiceResp" do
      optional :payment_request, :string, 1
    end
    add_message "invoicesrpc.SettleInvoiceMsg" do
      optional :preimage, :bytes, 1
    end
    add_message "invoicesrpc.SettleInvoiceResp" do
    end
    add_message "invoicesrpc.SubscribeSingleInvoiceRequest" do
      optional :r_hash, :bytes, 2
    end
  end
end

module Invoicesrpc
  CancelInvoiceMsg = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("invoicesrpc.CancelInvoiceMsg").msgclass
  CancelInvoiceResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("invoicesrpc.CancelInvoiceResp").msgclass
  AddHoldInvoiceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("invoicesrpc.AddHoldInvoiceRequest").msgclass
  AddHoldInvoiceResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("invoicesrpc.AddHoldInvoiceResp").msgclass
  SettleInvoiceMsg = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("invoicesrpc.SettleInvoiceMsg").msgclass
  SettleInvoiceResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("invoicesrpc.SettleInvoiceResp").msgclass
  SubscribeSingleInvoiceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("invoicesrpc.SubscribeSingleInvoiceRequest").msgclass
end
