# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peersrpc/peers.proto

require 'google/protobuf'

require 'lightning_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("peersrpc/peers.proto", :syntax => :proto3) do
    add_message "peersrpc.UpdateAddressAction" do
      optional :action, :enum, 1, "peersrpc.UpdateAction"
      optional :address, :string, 2
    end
    add_message "peersrpc.UpdateFeatureAction" do
      optional :action, :enum, 1, "peersrpc.UpdateAction"
      optional :feature_bit, :enum, 2, "lnrpc.FeatureBit"
    end
    add_message "peersrpc.NodeAnnouncementUpdateRequest" do
      repeated :feature_updates, :message, 1, "peersrpc.UpdateFeatureAction"
      optional :color, :string, 2
      optional :alias, :string, 3
      repeated :address_updates, :message, 4, "peersrpc.UpdateAddressAction"
    end
    add_message "peersrpc.NodeAnnouncementUpdateResponse" do
      repeated :ops, :message, 1, "lnrpc.Op"
    end
    add_enum "peersrpc.UpdateAction" do
      value :ADD, 0
      value :REMOVE, 1
    end
    add_enum "peersrpc.FeatureSet" do
      value :SET_INIT, 0
      value :SET_LEGACY_GLOBAL, 1
      value :SET_NODE_ANN, 2
      value :SET_INVOICE, 3
      value :SET_INVOICE_AMP, 4
    end
  end
end

module Peersrpc
  UpdateAddressAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("peersrpc.UpdateAddressAction").msgclass
  UpdateFeatureAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("peersrpc.UpdateFeatureAction").msgclass
  NodeAnnouncementUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("peersrpc.NodeAnnouncementUpdateRequest").msgclass
  NodeAnnouncementUpdateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("peersrpc.NodeAnnouncementUpdateResponse").msgclass
  UpdateAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("peersrpc.UpdateAction").enummodule
  FeatureSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("peersrpc.FeatureSet").enummodule
end
