# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autopilotrpc/autopilot.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("autopilotrpc/autopilot.proto", :syntax => :proto3) do
    add_message "autopilotrpc.StatusRequest" do
    end
    add_message "autopilotrpc.StatusResponse" do
      optional :active, :bool, 1
    end
    add_message "autopilotrpc.ModifyStatusRequest" do
      optional :enable, :bool, 1
    end
    add_message "autopilotrpc.ModifyStatusResponse" do
    end
    add_message "autopilotrpc.QueryScoresRequest" do
      repeated :pubkeys, :string, 1
      optional :ignore_local_state, :bool, 2
    end
    add_message "autopilotrpc.QueryScoresResponse" do
      repeated :results, :message, 1, "autopilotrpc.QueryScoresResponse.HeuristicResult"
    end
    add_message "autopilotrpc.QueryScoresResponse.HeuristicResult" do
      optional :heuristic, :string, 1
      map :scores, :string, :double, 2
    end
    add_message "autopilotrpc.SetScoresRequest" do
      optional :heuristic, :string, 1
      map :scores, :string, :double, 2
    end
    add_message "autopilotrpc.SetScoresResponse" do
    end
  end
end

module Autopilotrpc
  StatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("autopilotrpc.StatusRequest").msgclass
  StatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("autopilotrpc.StatusResponse").msgclass
  ModifyStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("autopilotrpc.ModifyStatusRequest").msgclass
  ModifyStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("autopilotrpc.ModifyStatusResponse").msgclass
  QueryScoresRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("autopilotrpc.QueryScoresRequest").msgclass
  QueryScoresResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("autopilotrpc.QueryScoresResponse").msgclass
  QueryScoresResponse::HeuristicResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("autopilotrpc.QueryScoresResponse.HeuristicResult").msgclass
  SetScoresRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("autopilotrpc.SetScoresRequest").msgclass
  SetScoresResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("autopilotrpc.SetScoresResponse").msgclass
end
