# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: watchtowerrpc/watchtower.proto for package 'watchtowerrpc'

require 'grpc'
require 'watchtowerrpc/watchtower_pb'

module Watchtowerrpc
  module Watchtower
    # Watchtower is a service that grants access to the watchtower server
    # functionality of the daemon.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'watchtowerrpc.Watchtower'

      # lncli: tower info
      # GetInfo returns general information concerning the companion watchtower
      # including its public key and URIs where the server is currently
      # listening for clients.
      rpc :GetInfo, ::Watchtowerrpc::GetInfoRequest, ::Watchtowerrpc::GetInfoResponse
    end

    Stub = Service.rpc_stub_class
  end
end
