# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watchtowerrpc/watchtower.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("watchtowerrpc/watchtower.proto", :syntax => :proto3) do
    add_message "watchtowerrpc.GetInfoRequest" do
    end
    add_message "watchtowerrpc.GetInfoResponse" do
      optional :pubkey, :bytes, 1
      repeated :listeners, :string, 2
      repeated :uris, :string, 3
    end
  end
end

module Watchtowerrpc
  GetInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("watchtowerrpc.GetInfoRequest").msgclass
  GetInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("watchtowerrpc.GetInfoResponse").msgclass
end
