# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: verrpc/verrpc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("verrpc/verrpc.proto", :syntax => :proto3) do
    add_message "verrpc.VersionRequest" do
    end
    add_message "verrpc.Version" do
      optional :commit, :string, 1
      optional :commit_hash, :string, 2
      optional :version, :string, 3
      optional :app_major, :uint32, 4
      optional :app_minor, :uint32, 5
      optional :app_patch, :uint32, 6
      optional :app_pre_release, :string, 7
      repeated :build_tags, :string, 8
      optional :go_version, :string, 9
    end
  end
end

module Verrpc
  VersionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("verrpc.VersionRequest").msgclass
  Version = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("verrpc.Version").msgclass
end
