# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stateservice.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("stateservice.proto", :syntax => :proto3) do
    add_message "lnrpc.SubscribeStateRequest" do
    end
    add_message "lnrpc.SubscribeStateResponse" do
      optional :state, :enum, 1, "lnrpc.WalletState"
    end
    add_message "lnrpc.GetStateRequest" do
    end
    add_message "lnrpc.GetStateResponse" do
      optional :state, :enum, 1, "lnrpc.WalletState"
    end
    add_enum "lnrpc.WalletState" do
      value :NON_EXISTING, 0
      value :LOCKED, 1
      value :UNLOCKED, 2
      value :RPC_ACTIVE, 3
      value :SERVER_ACTIVE, 4
      value :WAITING_TO_START, 255
    end
  end
end

module Lnrpc
  SubscribeStateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("lnrpc.SubscribeStateRequest").msgclass
  SubscribeStateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("lnrpc.SubscribeStateResponse").msgclass
  GetStateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("lnrpc.GetStateRequest").msgclass
  GetStateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("lnrpc.GetStateResponse").msgclass
  WalletState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("lnrpc.WalletState").enummodule
end
